<div class="elementor-element elementor-element-72ce4c6 elementor-widget__width-auto elementor-hidden-mobile elementor-widget elementor-widget-jet-mega-menu is-mac" data-id="72ce4c6" data-element_type="widget" data-widget_type="jet-mega-menu.default">
    <div class="elementor-widget-container">
        <div class="menu-main-menu-container">
            <div class="jet-menu-container">
                <div class="jet-menu-inner">
                    <ul class="jet-menu jet-menu--animation-type-fade jet-menu--roll-up">
                        <li id="jet-menu-item-21" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-menu-item-home jet-current-menu-item jet-page_item jet-page-item-1799 jet-current_page_item jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-21"><a href="http://www.ibogaspirit.cz/" class="top-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Home</div></div></a></li>
                        <li id="jet-menu-item-25" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-menu-item-has-children jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-25"><a href="http://www.ibogaspirit.cz/services/" class="top-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Iboga</div><i class="jet-dropdown-arrow fa fa-angle-down"></i></div></a>
                            <ul class="jet-sub-menu">
                                <li id="jet-menu-item-226" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-226 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/services/worldwide-transport/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Jak vám Iboga může pomoci</div></div></a></li>
                                <li id="jet-menu-item-1314" class="jet-menu-item jet-menu-item-type-custom jet-menu-item-object-custom jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1314 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/services/door-to-door-delivery/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Gabon</div></div></a></li>
                                <li id="jet-menu-item-1315" class="jet-menu-item jet-menu-item-type-custom jet-menu-item-object-custom jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1315 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/services/packaging-storage/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Bwiti Tradice</div></div></a></li>
                                <li id="jet-menu-item-1859" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1859 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/iboga-vs-ayahuasca/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Iboga vs Ayahuasca</div></div></a></li>
                            </ul>
                        </li>
                        <li id="jet-menu-item-1853" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-menu-item-has-children jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1853"><a href="http://www.ibogaspirit.cz/obrady/" class="top-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Obřady</div><i class="jet-dropdown-arrow fa fa-angle-down"></i></div></a>
                            <ul class="jet-sub-menu">
                                <li id="jet-menu-item-2078" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-2078 jet-sub-menu-item"><a title="Co očekávat" href="http://www.ibogaspirit.cz/obrady/co-ocekavat/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Co očekávat</div></div></a></li>
                                <li id="jet-menu-item-1312" class="jet-menu-item jet-menu-item-type-custom jet-menu-item-object-custom jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1312 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/services/iboga-ceremonie/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Vše o Obřadech</div></div></a></li>
                                <li id="jet-menu-item-1313" class="jet-menu-item jet-menu-item-type-custom jet-menu-item-object-custom jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1313 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/services/ground-transport/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Příprava a Průběžná péče</div></div></a></li>
                                <li id="jet-menu-item-1316" class="jet-menu-item jet-menu-item-type-custom jet-menu-item-object-custom jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1316 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/services/cargo/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Terminy a ceny</div></div></a></li>
                            </ul>
                        </li>
                        <li id="jet-menu-item-23" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-menu-item-has-children jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-23"><a href="http://www.ibogaspirit.cz/about/" class="top-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">O nás</div><i class="jet-dropdown-arrow fa fa-angle-down"></i></div></a>
                            <ul class="jet-sub-menu">
                                <li id="jet-menu-item-1850" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1850 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/nganga-lecitel/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Nganga (Léčitel)</div></div></a></li>
                                <li id="jet-menu-item-1834" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-1834 jet-sub-menu-item"><a href="http://www.ibogaspirit.cz/moughenda/" class="sub-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Šaman Moughenda</div></div></a></li>
                            </ul>
                        </li>
                        <li id="jet-menu-item-24" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-24"><a href="http://www.ibogaspirit.cz/contacts/" class="top-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Kontakt</div></div></a></li>
                        <li id="jet-menu-item-22" class="jet-menu-item jet-menu-item-type-post_type jet-menu-item-object-page jet-has-roll-up jet-simple-menu-item jet-regular-item jet-menu-item-22"><a href="http://www.ibogaspirit.cz/blog/" class="top-level-link"><div class="jet-menu-item-wrapper"><div class="jet-menu-title">Blog</div></div></a></li>
                        <li class="jet-menu-item jet-menu-item-has-children jet-simple-menu-item jet-responsive-menu-available-items jet-empty" hidden="hidden" style=""><a href="#" class="top-level-link"><div class="jet-menu-item-wrapper">···</div></a><ul class="jet-sub-menu"></ul></li></ul></div></div></div>		</div>
</div>
<div class="elementor-element elementor-element-73f4ca5 elementor-widget__width-auto elementor-hidden-desktop elementor-hidden-tablet elementor-widget elementor-widget-jet-mega-menu is-mac" data-id="73f4ca5" data-element_type="widget" data-widget_type="jet-mega-menu.default">
    <div class="elementor-widget-container" onclick="window.alert('YES');testFunction();">
        <div id="jet-mobile-menu-636731400893a" data-menu-id="11" data-menu-options="{&quot;menuUniqId&quot;:&quot;636731400893a&quot;,&quot;menuId&quot;:&quot;11&quot;,&quot;mobileMenuId&quot;:&quot;3&quot;,&quot;location&quot;:&quot;wp-nav&quot;,&quot;menuLocation&quot;:false,&quot;menuLayout&quot;:&quot;slide-out&quot;,&quot;togglePosition&quot;:&quot;default&quot;,&quot;menuPosition&quot;:&quot;right&quot;,&quot;headerTemplate&quot;:&quot;&quot;,&quot;beforeTemplate&quot;:&quot;&quot;,&quot;afterTemplate&quot;:&quot;&quot;,&quot;useBreadcrumb&quot;:false,&quot;breadcrumbPath&quot;:&quot;full&quot;,&quot;toggleText&quot;:&quot;&quot;,&quot;toggleLoader&quot;:true,&quot;backText&quot;:&quot;&quot;,&quot;itemIconVisible&quot;:false,&quot;itemBadgeVisible&quot;:false,&quot;itemDescVisible&quot;:false,&quot;loaderColor&quot;:&quot;#242426&quot;,&quot;subTrigger&quot;:&quot;submarker&quot;,&quot;subOpenLayout&quot;:&quot;slide-in&quot;,&quot;closeAfterNavigate&quot;:false}" class="jet-mobile-menu jet-mobile-menu--location-wp-nav"><div class="jet-mobile-menu__instance jet-mobile-menu__instance--slide-out-layout right-container-position default-toggle-position"><div tabindex="1" aria-label="Open/Close Menu" class="jet-mobile-menu__toggle"><!----> <div class="jet-mobile-menu__toggle-icon"><i class="fas fa-bars"></i></div> <!----> <!----></div> <!----> <!----></div><div class="jet-mobile-menu__refs"><div><i class="fas fa-bars"></i></div><div><i class="fas fa-times"></i></div><div><i class="fas fa-times"></i></div><div><i class="fas fa-angle-left"></i></div><div><i class="fas fa-angle-right"></i></div><div><i class="fas fa-angle-down"></i></div><div><i class="fas fa-angle-right"></i></div></div></div>		</div>
</div>
